name: CI

on:
  push:
    branches: [ develop ]

env:
  BUILD_TYPE: Debug

jobs:
  cppcheck:
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: run cppcheck
        uses: deep5050/cppcheck-action@v3.0
        with:
          std: c++17

  clang-tidy:
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: run clang-tidy
        uses: cpp-linter/cpp-linter-action@v2.4.2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          style: file
          extra-args: -std=c++17
